[2024-01-26 22:22:56,861: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-26 22:22:56,867: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-26 22:22:56,876: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-26 22:22:56,876: INFO: common: created directory at: artifacts]
[2024-01-26 22:22:56,877: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-26 22:22:56,878: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-26 22:36:04,099: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-26 22:36:05,285: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:27:38,357: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:27:38,367: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:27:38,369: INFO: common: created directory at: artifacts]
[2024-01-27 19:27:38,371: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:30:47,736: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:30:47,738: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:30:47,740: INFO: common: created directory at: artifacts]
[2024-01-27 19:30:47,742: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:31:38,242: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 19:41:40,071: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 19:41:40,073: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:41:40,076: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:41:40,077: INFO: common: created directory at: artifacts]
[2024-01-27 19:41:40,077: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 19:41:40,078: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:42:29,771: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:42:30,324: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:44:08,865: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 19:44:08,867: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:44:08,869: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:44:08,869: INFO: common: created directory at: artifacts]
[2024-01-27 19:44:08,871: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 19:44:08,871: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:45:08,879: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 19:45:09,446: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 19:45:09,446: INFO: main: *******************]
[2024-01-27 19:45:09,446: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 19:45:09,448: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 19:45:09,451: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 19:45:09,452: INFO: common: created directory at: artifacts]
[2024-01-27 19:45:09,452: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 19:45:09,865: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 19:45:10,110: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:18:18,296: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:18:18,309: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:18:18,316: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:18:18,317: INFO: common: created directory at: artifacts]
[2024-01-27 20:18:18,317: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:18:18,318: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:19:20,786: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:19:21,327: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:19:21,328: INFO: main: *******************]
[2024-01-27 20:19:21,328: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:19:21,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:19:21,333: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:19:21,334: INFO: common: created directory at: artifacts]
[2024-01-27 20:19:21,335: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:19:21,807: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:19:22,131: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:20:40,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:20:40,834: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:20:40,837: INFO: common: created directory at: artifacts]
[2024-01-27 20:20:40,839: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:23:11,828: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:23:11,833: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:23:11,834: INFO: common: created directory at: artifacts]
[2024-01-27 20:23:11,836: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:41:43,007: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:41:43,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:41:43,013: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:41:43,014: INFO: common: created directory at: artifacts]
[2024-01-27 20:41:43,014: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:41:43,015: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:43:20,655: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:43:21,291: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:43:21,292: INFO: main: *******************]
[2024-01-27 20:43:21,292: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:43:21,294: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:43:21,297: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:43:21,297: INFO: common: created directory at: artifacts]
[2024-01-27 20:43:21,298: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:43:21,745: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:43:22,206: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:43:22,207: INFO: main: *******************]
[2024-01-27 20:43:22,207: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-27 20:43:22,209: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:43:22,212: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:43:22,213: INFO: common: created directory at: artifacts]
[2024-01-27 20:43:22,214: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:43:22,214: ERROR: main: "'ConfigBox' object has no attribute 'epochs'"]
Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'EPOCHS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'EPOCHS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'EPOCHS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\config_box.py", line 28, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'EPOCHS'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 503, in box.box.Box.__getitem__
KeyError: 'epochs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "box\box.py", line 536, in box.box.Box.__getattr__
  File "box\box.py", line 524, in box.box.Box.__getitem__
box.exceptions.BoxKeyError: "'epochs'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "box\box.py", line 538, in box.box.Box.__getattr__
AttributeError: 'ConfigBox' object has no attribute 'epochs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 33, in <module>
    model_trainer.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_03_model_training.py", line 17, in main
    training_config = config.get_training_config()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\config\configuration.py", line 66, in get_training_config
    params_epochs=params.EPOCHS,
  File "box\config_box.py", line 30, in box.config_box.ConfigBox.__getattr__
  File "box\box.py", line 552, in box.box.Box.__getattr__
box.exceptions.BoxKeyError: "'ConfigBox' object has no attribute 'epochs'"
[2024-01-27 20:45:14,586: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:45:14,594: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:45:14,596: INFO: common: created directory at: artifacts]
[2024-01-27 20:45:14,597: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:46:27,095: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-01-27 20:46:27,098: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:46:27,100: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:46:27,101: INFO: common: created directory at: artifacts]
[2024-01-27 20:46:27,102: INFO: common: created directory at: artifacts/data_ingestion]
[2024-01-27 20:46:27,103: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:48:00,945: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-01-27 20:48:01,577: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-01-27 20:48:01,577: INFO: main: *******************]
[2024-01-27 20:48:01,578: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-01-27 20:48:01,580: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:48:01,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:48:01,582: INFO: common: created directory at: artifacts]
[2024-01-27 20:48:01,583: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-01-27 20:48:02,086: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-01-27 20:48:02,377: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-01-27 20:48:02,378: INFO: main: *******************]
[2024-01-27 20:48:02,378: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-01-27 20:48:02,381: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-01-27 20:48:02,384: INFO: common: yaml file: params.yaml loaded successfully]
[2024-01-27 20:48:02,385: INFO: common: created directory at: artifacts]
[2024-01-27 20:48:02,386: INFO: common: created directory at: artifacts\training]
[2024-01-27 20:48:39,543: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-02-08 22:57:57,834: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 22:57:57,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 22:57:57,853: INFO: common: created directory at: artifacts]
[2024-02-08 22:58:17,466: INFO: common: json file saved at: scores.json]
[2024-02-08 22:58:28,258: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-08 22:58:29,842: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpouszrem3\model\data\model\assets]
[2024-02-08 23:02:00,819: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/95841584265043d1baabf1dcf05389f0/41070d4228a0474cbe4853a586caa5fb/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-08 23:07:39,422: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:07:39,430: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:07:39,432: INFO: common: created directory at: artifacts]
[2024-02-08 23:07:57,806: INFO: common: json file saved at: scores.json]
[2024-02-08 23:08:19,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:08:19,614: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:08:19,618: INFO: common: created directory at: artifacts]
[2024-02-08 23:08:37,887: INFO: common: json file saved at: scores.json]
[2024-02-08 23:09:14,841: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:09:14,849: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:09:14,853: INFO: common: created directory at: artifacts]
[2024-02-08 23:09:33,888: INFO: common: json file saved at: scores.json]
[2024-02-08 23:11:42,937: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:11:42,953: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:11:42,957: INFO: common: created directory at: artifacts]
[2024-02-08 23:12:02,071: INFO: common: json file saved at: scores.json]
[2024-02-08 23:12:02,224: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'RemoteDisconnected('Remote end closed connection without response')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow/runs/create]
[2024-02-08 23:13:23,707: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-08 23:13:23,714: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-08 23:13:23,718: INFO: common: created directory at: artifacts]
[2024-02-08 23:13:42,966: INFO: common: json file saved at: scores.json]
[2024-02-09 00:53:52,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 00:53:52,878: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 00:53:52,881: INFO: common: created directory at: artifacts]
[2024-02-09 00:54:11,859: INFO: common: json file saved at: scores.json]
[2024-02-09 11:13:58,245: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:13:58,256: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:13:58,259: INFO: common: created directory at: artifacts]
[2024-02-09 11:14:17,423: INFO: common: json file saved at: scores.json]
[2024-02-09 11:17:39,154: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:17:39,168: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:17:39,171: INFO: common: created directory at: artifacts]
[2024-02-09 11:17:57,530: INFO: common: json file saved at: scores.json]
[2024-02-09 11:27:31,575: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:27:31,582: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:27:31,585: INFO: common: created directory at: artifacts]
[2024-02-09 11:27:49,751: INFO: common: json file saved at: scores.json]
[2024-02-09 11:47:48,687: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 11:47:48,695: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 11:47:48,699: INFO: common: created directory at: artifacts]
[2024-02-09 11:48:07,276: INFO: common: json file saved at: scores.json]
[2024-02-09 20:47:58,913: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 20:47:58,921: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 20:47:58,924: INFO: common: created directory at: artifacts]
[2024-02-09 20:48:19,757: INFO: common: json file saved at: scores.json]
[2024-02-09 21:08:45,800: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 21:08:45,811: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 21:08:45,813: INFO: common: created directory at: artifacts]
[2024-02-09 21:09:01,021: INFO: common: json file saved at: scores.json]
[2024-02-09 21:09:05,770: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 21:09:06,583: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmp9ins6pol\model\data\model\assets]
[2024-02-09 21:10:42,423: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:13:51,097: WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:14:30,243: WARNING: connectionpool: Retrying (Retry(total=2, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:24:25,752: WARNING: connectionpool: Retrying (Retry(total=1, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/d779d3e651874f389885ca13a5ea937f/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:28:57,926: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 21:28:57,930: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 21:28:57,933: INFO: common: created directory at: artifacts]
[2024-02-09 21:29:11,025: INFO: common: json file saved at: scores.json]
[2024-02-09 21:29:15,545: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 21:29:16,252: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmptb9a8j0v\model\data\model\assets]
[2024-02-09 21:36:00,741: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-02-09 21:36:00,753: INFO: common: yaml file: params.yaml loaded successfully]
[2024-02-09 21:36:00,755: INFO: common: created directory at: artifacts]
[2024-02-09 21:36:13,747: INFO: common: json file saved at: scores.json]
[2024-02-09 21:36:18,736: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-02-09 21:36:19,526: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpy5yxb823\model\data\model\assets]
[2024-02-09 21:43:25,646: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/c263475b1fd344f3bf038506c5640f51/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-02-09 21:44:00,771: WARNING: connectionpool: Retrying (Retry(total=3, connect=5, read=5, redirect=5, status=5)) after connection broken by 'SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')': /Siamias202/kidney_disease_detection.mlflow/api/2.0/mlflow-artifacts/artifacts/e33da3fbd6fd4dbca196d26da02ae894/c263475b1fd344f3bf038506c5640f51/artifacts/model/data/model/variables/variables.data-00000-of-00001]
[2024-03-01 19:07:22,793: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-01 19:07:22,802: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:07:22,810: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:07:22,811: INFO: common: created directory at: artifacts]
[2024-03-01 19:07:22,812: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-01 19:07:22,813: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:08:15,735: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:08:16,798: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-01 19:08:16,798: INFO: main: *******************]
[2024-03-01 19:08:16,798: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-01 19:08:16,804: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:08:16,808: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:08:16,809: INFO: common: created directory at: artifacts]
[2024-03-01 19:08:16,810: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-01 19:08:17,864: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-01 19:08:18,484: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-01 19:08:18,485: INFO: main: *******************]
[2024-03-01 19:08:18,486: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-01 19:08:18,491: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:08:18,496: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:08:18,497: INFO: common: created directory at: artifacts]
[2024-03-01 19:08:18,498: INFO: common: created directory at: artifacts\training]
[2024-03-01 19:09:14,747: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-01 19:09:14,747: INFO: main: *******************]
[2024-03-01 19:09:14,747: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-01 19:09:14,753: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:09:14,755: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:09:14,756: INFO: common: created directory at: artifacts]
[2024-03-01 19:09:33,184: INFO: common: json file saved at: scores.json]
[2024-03-01 19:09:33,185: INFO: common: json file saved at: scores.json]
[2024-03-01 19:09:33,186: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-01 19:15:55,829: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-01 19:15:55,835: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:15:55,851: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:15:55,852: INFO: common: created directory at: artifacts]
[2024-03-01 19:15:55,854: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-01 19:15:55,855: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:20:47,614: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:20:48,897: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-01 19:20:48,899: INFO: main: *******************]
[2024-03-01 19:20:48,899: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-01 19:20:48,905: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:20:48,909: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:20:48,910: INFO: common: created directory at: artifacts]
[2024-03-01 19:20:48,911: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-01 19:20:50,048: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-01 19:20:50,954: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-01 19:20:50,956: INFO: main: *******************]
[2024-03-01 19:20:50,957: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-01 19:20:50,961: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:20:50,967: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:20:50,968: INFO: common: created directory at: artifacts]
[2024-03-01 19:20:50,970: INFO: common: created directory at: artifacts\training]
[2024-03-01 19:25:34,788: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-01 19:25:34,789: INFO: main: *******************]
[2024-03-01 19:25:34,790: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-01 19:25:34,795: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:25:34,801: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:25:34,802: INFO: common: created directory at: artifacts]
[2024-03-01 19:25:52,897: INFO: common: json file saved at: scores.json]
[2024-03-01 19:25:52,898: INFO: common: json file saved at: scores.json]
[2024-03-01 19:25:52,899: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-01 19:26:59,219: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-01 19:26:59,225: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:26:59,242: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:26:59,243: INFO: common: created directory at: artifacts]
[2024-03-01 19:26:59,245: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-01 19:26:59,246: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:28:11,635: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 19:28:12,895: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-01 19:28:12,896: INFO: main: *******************]
[2024-03-01 19:28:12,897: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-01 19:28:12,903: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:28:12,909: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:28:12,910: INFO: common: created directory at: artifacts]
[2024-03-01 19:28:12,911: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-01 19:28:13,909: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-01 19:28:14,463: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-01 19:28:14,464: INFO: main: *******************]
[2024-03-01 19:28:14,464: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-01 19:28:14,471: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:28:14,475: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:28:14,476: INFO: common: created directory at: artifacts]
[2024-03-01 19:28:14,478: INFO: common: created directory at: artifacts\training]
[2024-03-01 19:31:04,656: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-01 19:31:04,657: INFO: main: *******************]
[2024-03-01 19:31:04,658: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-01 19:31:04,663: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:31:04,668: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:31:04,669: INFO: common: created directory at: artifacts]
[2024-03-01 19:31:22,690: INFO: common: json file saved at: scores.json]
[2024-03-01 19:31:22,691: INFO: common: json file saved at: scores.json]
[2024-03-01 19:31:22,693: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-01 19:40:07,896: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 19:40:07,904: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 19:40:07,906: INFO: common: created directory at: artifacts]
[2024-03-01 19:40:27,009: INFO: common: json file saved at: scores.json]
[2024-03-01 19:40:33,723: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-01 19:40:35,303: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmprqvjqd3n\model\data\model\assets]
[2024-03-01 20:25:04,543: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 20:25:04,552: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 20:25:04,554: INFO: common: created directory at: artifacts]
[2024-03-01 20:25:17,919: INFO: common: json file saved at: scores.json]
[2024-03-01 20:25:26,805: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-03-01 20:25:27,538: INFO: builder_impl: Assets written to: C:\Users\User\AppData\Local\Temp\tmpcysokez1\model\data\model\assets]
[2024-03-01 21:52:24,180: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-01 21:52:24,196: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 21:52:24,196: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 21:52:24,196: INFO: common: created directory at: artifacts]
[2024-03-01 21:52:24,196: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-01 21:52:24,212: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 21:54:14,753: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-01 21:54:15,925: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-01 21:54:15,925: INFO: main: *******************]
[2024-03-01 21:54:15,925: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-01 21:54:15,925: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 21:54:15,925: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 21:54:15,935: INFO: common: created directory at: artifacts]
[2024-03-01 21:54:15,935: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-01 21:54:16,878: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-01 21:54:17,236: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-01 21:54:17,236: INFO: main: *******************]
[2024-03-01 21:54:17,238: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-03-01 21:54:17,243: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 21:54:17,247: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 21:54:17,248: INFO: common: created directory at: artifacts]
[2024-03-01 21:54:17,249: INFO: common: created directory at: artifacts\training]
[2024-03-01 22:03:02,962: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-01 22:03:02,962: INFO: main: *******************]
[2024-03-01 22:03:02,962: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-01 22:03:02,971: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-01 22:03:02,978: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-01 22:03:02,979: INFO: common: created directory at: artifacts]
[2024-03-01 22:03:20,596: INFO: common: json file saved at: scores.json]
[2024-03-01 22:03:20,597: INFO: common: json file saved at: scores.json]
[2024-03-01 22:03:20,599: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-02 11:27:31,302: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-02 11:27:31,305: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-02 11:27:31,307: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-02 11:27:31,308: INFO: common: created directory at: artifacts]
[2024-03-02 11:27:31,308: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-02 11:27:31,308: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-02 11:28:26,034: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-02 11:28:26,651: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-02 11:28:44,466: INFO: stage_02_prepare_base_model: *******************]
[2024-03-02 11:28:44,467: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-02 11:28:44,470: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-02 11:28:44,472: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-02 11:28:44,472: INFO: common: created directory at: artifacts]
[2024-03-02 11:28:44,472: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-02 11:28:45,143: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-02 11:28:45,430: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-03-02 11:28:52,338: INFO: stage_03_model_training: *******************]
[2024-03-02 11:28:52,339: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-02 11:28:52,341: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-02 11:28:52,345: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-02 11:28:52,345: INFO: common: created directory at: artifacts]
[2024-03-02 11:28:52,346: INFO: common: created directory at: artifacts\training]
[2024-03-02 11:35:49,915: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-03-02 11:35:58,995: INFO: stage_04_model_evaluation: *******************]
[2024-03-02 11:35:58,996: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage started <<<<<<]
[2024-03-02 11:35:58,998: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-02 11:35:59,000: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-02 11:35:59,000: INFO: common: created directory at: artifacts]
[2024-03-02 11:36:13,060: INFO: common: json file saved at: scores.json]
[2024-03-02 11:36:13,061: INFO: common: json file saved at: scores.json]
[2024-03-02 11:36:13,062: INFO: stage_04_model_evaluation: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-03-02 12:33:51,605: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000019E14295B40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-02 12:34:05,510: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x0000019E14295AB0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-02 13:59:15,346: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001BD1DD1AE60> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 18:46:35,943: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D706986830> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 18:46:45,544: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000001D706985870> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-03-08 19:05:34,107: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 19:05:34,108: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 19:05:40,000: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:05:40] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:06:15,394: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:06:15] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:07:26,882: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:07:26] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:07:44,166: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.103:8080]
[2024-03-08 19:07:44,168: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-03-08 19:07:47,856: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:07:47] "GET / HTTP/1.1" 200 -]
[2024-03-08 19:07:55,391: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:07:55] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:08:43,276: INFO: _internal: 192.168.0.103 - - [08/Mar/2024 19:08:43] "POST /predict HTTP/1.1" 200 -]
[2024-03-08 19:10:56,441: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:10:56,457: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:10:56,461: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:10:56,462: INFO: common: created directory at: artifacts]
[2024-03-08 19:10:56,463: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:10:56,464: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:10:59,794: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:11:32,856: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:11:32,861: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:11:32,868: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:11:32,869: INFO: common: created directory at: artifacts]
[2024-03-08 19:11:32,870: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:11:32,871: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:11:35,425: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:15:00,016: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:15:00,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:15:00,024: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:15:00,024: INFO: common: created directory at: artifacts]
[2024-03-08 19:15:00,025: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:15:00,025: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:15:03,274: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:16:22,957: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-08 19:16:22,960: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:16:22,962: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:16:22,963: INFO: common: created directory at: artifacts]
[2024-03-08 19:16:22,963: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-08 19:16:22,963: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-08 19:16:25,141: ERROR: main: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.]
Traceback (most recent call last):
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 221, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 47, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ML Project\kidney_disease_detection\main.py", line 14, in <module>
    data_ingestion.main()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 15, in main
    data_ingestion.download_file()
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 33, in download_file
    raise e
  File "e:\ml project\kidney_disease_detection\src\cnnClassifier\components\data_ingestion.py", line 28, in download_file
    gdown.download(prefix+file_id,zip_download_dir)
  File "D:\Anaconda_envs\envs\myenv\lib\site-packages\gdown\download.py", line 232, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?/export=download&id=1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3

but Gdown can't. Please check connections and permissions.
[2024-03-08 19:17:46,682: INFO: stage_03_model_training: *******************]
[2024-03-08 19:17:46,683: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2024-03-08 19:17:46,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-08 19:17:46,688: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-08 19:17:46,688: INFO: common: created directory at: artifacts]
[2024-03-08 19:17:46,689: INFO: common: created directory at: artifacts\training]
